FROM maven:3.9-eclipse-temurin-21 AS build

WORKDIR /app

# Copy only the payment-service module
COPY payment-service/pom.xml ./payment-service/
COPY payment-service/src ./payment-service/src

# Build the payment-service module
RUN mvn -f payment-service/pom.xml clean package -DskipTests

FROM eclipse-temurin:21-jre

WORKDIR /app
COPY --from=build /app/payment-service/target/*.jar app.jar

EXPOSE 8082
ENTRYPOINT ["java", "-jar", "app.jar"]
