FROM maven:3.9-eclipse-temurin-21 AS build
WORKDIR /app
COPY email-service/pom.xml ./email-service/
COPY email-service/src ./email-service/src
RUN mvn -f email-service/pom.xml clean package -DskipTests

FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /app/email-service/target/*.jar app.jar
EXPOSE 8088
ENTRYPOINT ["java", "-jar", "app.jar"]

