FROM maven:3.9-eclipse-temurin-21 AS build

WORKDIR /app

# Copy only the accounts-service module
COPY accounts-service/pom.xml ./accounts-service/
COPY accounts-service/src ./accounts-service/src

# Build the accounts-service module
RUN mvn -f accounts-service/pom.xml clean package -DskipTests

FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /app/accounts-service/target/*.jar app.jar
EXPOSE 8087
ENTRYPOINT ["java", "-jar", "app.jar"]
